runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /img
  static_dir: static/image

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /.*
  script: main.app
  secure: always
